# Generated by Django 4.2.16 on 2024-11-20 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recursos', '0002_asignatura_creador_grupo_creador_local_creador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.PositiveSmallIntegerField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recursos.grupo')),
            ],
            options={
                'unique_together': {('grupo', 'semana')},
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('clase', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recursos.asignatura')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('horario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='Editor.horario')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recursos.local')),
            ],
        ),
    ]
