# Generated by Django 4.2.16 on 2024-11-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='tipo',
            field=models.CharField(choices=[('CP', 'Clase Practica'), ('C', 'Conferencia'), ('L', 'Laboratorio'), ('T', 'Taller'), ('S', 'Seminario')], default='C', max_length=2),
        ),
    ]
