# Generated by Django 4.2.16 on 2024-11-27 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recursos', '0005_remove_asignatura_tipo'),
        ('Editor', '0002_turno_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='horario',
        ),
        migrations.AddField(
            model_name='turno',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Recursos.grupo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turno',
            name='semana',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
