# Generated by Django 4.2.16 on 2024-11-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0005_alter_horario_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
