# Generated by Django 5.2 on 2025-05-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0006_horario_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='profesores_ids',
            field=models.CharField(blank=True, default='', help_text='IDs de profesores asociados separados por comas (ej: 1,5,7)', max_length=255, verbose_name='IDs de Profesores'),
        ),
    ]
