# Generated by Django 5.2 on 2025-05-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Editor', '0007_horario_profesores_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='profesores_ids',
        ),
    ]
