# Generated by Django 4.2.16 on 2024-11-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0002_usuario_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='año',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
