# Generated by Django 4.2.16 on 2024-11-15 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CP', 'Clase Practica'), ('C', 'Conferencia'), ('L', 'Laboratorio'), ('T', 'Taller'), ('S', 'Seminario')], default='C', max_length=2)),
                ('siglas', models.CharField(default='', max_length=10)),
                ('nombre', models.CharField(max_length=253)),
                ('catedra', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.PositiveSmallIntegerField(default=3)),
                ('year', models.PositiveSmallIntegerField(default=1)),
                ('grupo', models.PositiveSmallIntegerField(default=1)),
                ('matricula', models.PositiveSmallIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'Aula'), ('SC', 'Salon de Conferencias'), ('L', 'Laboratorio')], default='A', max_length=2)),
                ('piso', models.PositiveSmallIntegerField(default=1)),
                ('codigo', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CP', 'Clase Practica'), ('C', 'Conferencia'), ('L', 'Laboratorio'), ('T', 'Taller'), ('S', 'Seminario')], default='C', max_length=2)),
                ('nombre', models.CharField(max_length=253)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Recursos.asignatura')),
            ],
        ),
    ]
