# Generated by Django 4.2.16 on 2024-11-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recursos', '0002_asignatura_creador_grupo_creador_local_creador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='codigo',
            new_name='numero',
        ),
    ]
