# Generated by Django 4.2.16 on 2024-11-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recursos', '0004_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='tipo',
        ),
    ]
