# Generated by Django 5.1.6 on 2025-05-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recursos', '0006_alter_balance_options_remove_balance_creador_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'permissions': [('can_manage_locales', 'Puede gestionar locales académicos')]},
        ),
        migrations.AlterUniqueTogether(
            name='local',
            unique_together={('tipo', 'piso', 'numero')},
        ),
        migrations.RemoveField(
            model_name='local',
            name='creador',
        ),
    ]
