# Generated by Django 5.2 on 2025-05-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recursos', '0007_alter_local_options_alter_local_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['siglas'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AddField(
            model_name='asignatura',
            name='clases_por_semana',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número de veces que esta asignatura se imparte cada semana', verbose_name='Clases por semana'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='clases_por_semestre',
            field=models.PositiveSmallIntegerField(default=15, help_text='Número total de clases que tendrá esta asignatura en el semestre', verbose_name='Clases por semestre'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='horario_preferente',
            field=models.CharField(choices=[('M', 'Mañana (8:00 AM - 12:30 PM)'), ('T', 'Tarde (12:30 PM - 4:50 PM)'), ('A', 'Ambos horarios')], default='A', help_text='Indica si la asignatura debe impartirse por la mañana, tarde o ambos', max_length=1, verbose_name='Horario preferente'),
        ),
    ]
