# Generated by Django 5.2 on 2025-05-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recursos', '0008_alter_asignatura_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='capacidad',
            field=models.PositiveSmallIntegerField(default=30, help_text='Cantidad máxima de personas que puede albergar', verbose_name='Capacidad'),
        ),
    ]
