# Generated by Django 5.2 on 2025-05-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recursos', '0009_local_capacidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AddField(
            model_name='profesor',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='profesores', to='Recursos.grupo'),
        ),
    ]
