# Generated by Django 5.2 on 2025-05-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recursos', '0010_alter_profesor_options_profesor_grupos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={},
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='grupos',
        ),
        migrations.AddField(
            model_name='profesor',
            name='grupos_ids',
            field=models.CharField(blank=True, default='', help_text='IDs de grupos asociados separados por comas (ej: 1,5,7)', max_length=255, verbose_name='IDs de Grupos'),
        ),
    ]
